### ISSUE TITLE
No OpenGraph.fetch function found

### ISSUE THREAD

**Issue by clsource** [bitboxer/opengraph_parser#56]
Hello The code documentation says

https://github.com/bitboxer/opengraph_parser/blob/82e60af5402c4634702ca33fe4fdc5c5118bc320/lib/open_graph.ex#L8

But I could not found any `OpenGraph.fetch` function.

In the original code it can be found though

https://github.com/andrielfn/open_graph/blob/master/lib/open_graph.ex#L28

Maybe it can be replaced the comments using

```elixir
Mix.install([
  {:opengraph_parser, "~> 0.4.4"},
  {:req, "~> 0.4.14"}
])

Req.get!("https://github.com").body
|> OpenGraph.parse()
```
Thanks :)

**Comment by bitboxer** [comment]
Ah, yes. I forgot to change that there. I decided not to have a fetch in my fork because of the tons of things people use to fetch the actual data.

Will fix that.
